### ISSUE TITLE
여기는 뭔가요?

### ISSUE THREAD

**Issue by injoon5** [Bukgeuk/bcloud-web#1]
둘러보다 찾았네요. 
혹시 저도 쓸 수 있을까요?

**Comment by jiunkong** [comment]
@injoon5 사용하는건 그냥 출처만 밝혀주시면 상관 없긴 합니다만
코드가 워낙 개판이라서.....

**Comment by injoon5** [comment]
아, 네. 
답장해주셔서 감사합니다.
